---
apiVersion: v1
kind: Namespace
metadata:
  name: pipeline-demo

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: myapis
  name: myapis
  namespace: pipeline-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapis
  template:
    metadata:
      labels:
        app: myapis
    spec:
      containers:
      - image: registry.innowi.com/myapis:<TAG>
        imagePullPolicy: Always
        name: myapis
      imagePullSecrets:
      - name: regcred          

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: myapis
  name: myapis
  namespace: pipeline-demo
spec:
  ports:
  - nodePort: 32280
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: myapis
  type: NodePort
